name: Makefile CI

on:
  push:
    branches: [ "cobalt" ]
  pull_request:
    branches: [ "cobalt" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install jq git patch sed binutils squashfs-tools rename findutils xz-utils

    - name: Install dependencies
      run: make PACKAGE=./ipks-official/2023-07-30-youtube.leanback.v4-1.1.7.ipk PACKAGE_NAME=sidereal.youtube.v1
      
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: IPK
        path: ./ipks-official/2023-07-30-youtube.leanback.v4-1.1.7-patched.ipk
