name: Makefile CI

on:
  push:
    branches: [ "cobalt" ]
  pull_request:
    branches: [ "cobalt" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install jq git patch sed binutils squashfs-tools rename findutils xz-utils

    - name: Install dependencies
      run: make PACKAGE=./your-tv-youtube.ipk PACKAGE_NAME=sidereal.youtube.v1
      
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: IPK
        path: your-tv-youtube.ipk
